# Elasticsearch Configuration for TestMaster

cluster.name: testmaster-cluster
node.name: elasticsearch

# Network
network.host: 0.0.0.0

# Discovery
discovery.type: single-node

# Security (disabled for development)
xpack.security.enabled: false
xpack.security.http.ssl.enabled: false

# Monitoring
xpack.monitoring.collection.enabled: true

# Index settings
action.auto_create_index: true
