# Prometheus Configuration for TestMaster

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'testmaster'
    environment: 'development'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  # - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # TestMaster API metrics
  - job_name: 'testmaster-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:3001']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'testmaster-api'

  # TestMaster Test Engine metrics
  - job_name: 'testmaster-test-engine'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:3002']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'testmaster-test-engine'
